const data = {
    products:[
        {
            _id:'1',
            name:'Grand Theft Auto V',
            genre:'action-adventure',
            image:'/images/igrica-1.jpg',
            price:'30.00',
            countInStock:'10',
            year:'2013',
        },
        {
            _id:'2',
            name:'Grand Theft Auto IV',
            genre:'action-adventure',
            image:'/images/igrica-2.jpg',
            price:'20.00',
            countInStock:'20',
            year:'2008',
        },
        {
            _id:'3',
            name:'Max Payne 3',
            genre:'action-adventure',
            image:'/images/igrica-3.jpg',
            price:'20.00',
            countInStock:'0',
            year:'2012',
        },
        {
            _id:'4',
            name:'Far Cry 3',
            genre:'first-person shooter',
            image:'/images/igrica-4.jpg',
            price:'12.00',
            countInStock:'15',
            year:'2012',
        },
        {
            _id:'5',
            name:'Far Cry 4',
            genre:'first-person shooter',
            image:'/images/igrica-5.jpg',
            price:'15.00',
            countInStock:'5',
            year:'2014',
        },
        {
            _id:'6',
            name:'FIFA 21',
            genre:'sports',
            image:'/images/igrica-6.jpg',
            price:'25.00',
            countInStock:'10',
            year:'2020',
        },
        {
            _id:'7',
            name:'Cyberpunk 2077',
            genre:'action role-playing',
            image:'/images/igrica-7.jpg',
            price:'45.00',
            countInStock:'12',
            year:'2020',
        },
        {
            _id:'8',
            name:'Red Dead Redemption 2',
            genre:'action-adventure',
            image:'/images/igrica-8.jpg',
            price:'40.00',
            countInStock:'7',
            year:'2018',
        },
    ]
}
export default data;